### PR TITLE
Support --expect-body-xpath in the http command

### PR DESCRIPTION
**Pull request by mortymacs**

### CODE REVIEW

**Comment by atkrad** [comment]
@mortymacs Could you please write some unit tests for the feature?

**Comment by mortymacs** [comment]
> @mortymacs Could you please write some unit tests for the feature?

Oh, I've forgotten to add it. I'll update the PR.

**Comment by mortymacs** [comment]
> @mortymacs Could you please write some unit tests for the feature?

Done

**Review by atkrad — APPROVED** [review]

**Comment by atkrad** [comment]
@mortymacs Could you please add its example to the README.md file and make a new PR?

**Comment by mortymacs** [comment]
> @mortymacs Could you please add its example to the README.md file and make a new PR?

Sorry I missed it.

**Pull request merged**
